"""auto update

Revision ID: 0bf42a4980ee
Revises: 
Create Date: 2026-05-29 03:14:15.506173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf42a4980ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('defense_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monster1', sa.String(), nullable=False),
    sa.Column('monster2', sa.String(), nullable=False),
    sa.Column('monster3', sa.String(), nullable=False),
    sa.Column('attack_type', sa.String(), nullable=False),
    sa.Column('success_rate', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('focus_order', sa.String(), nullable=True),
    sa.Column('tips', sa.String(), nullable=True),
    sa.Column('risks', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attacks_id'), 'attacks', ['id'], unique=False)
    op.create_table('defenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monster1', sa.String(), nullable=False),
    sa.Column('monster2', sa.String(), nullable=False),
    sa.Column('monster3', sa.String(), nullable=False),
    sa.Column('element1', sa.String(), nullable=False),
    sa.Column('element2', sa.String(), nullable=False),
    sa.Column('element3', sa.String(), nullable=False),
    sa.Column('tower', sa.String(), nullable=False),
    sa.Column('defense_type', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defenses_id'), 'defenses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_defenses_id'), table_name='defenses')
    op.drop_table('defenses')
    op.drop_index(op.f('ix_attacks_id'), table_name='attacks')
    op.drop_table('attacks')
    # ### end Alembic commands ###