"""auto update

Revision ID: a1b28974589c
Revises: 0bf42a4980ee
Create Date: 2026-05-29 07:10:55.131737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b28974589c'
down_revision: Union[str, Sequence[str], None] = '0bf42a4980ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attacks', sa.Column('season', sa.String(), nullable=True))
    op.add_column('defenses', sa.Column('season', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defenses', 'season')
    op.drop_column('attacks', 'season')
    # ### end Alembic commands ###